### ISSUE TITLE
Peer Review by Parth Samant 

### ISSUE THREAD

**Issue by samantparth** [Stella41603/Toronto-Speeding-Analysis#1]
**Summary**
This repo aims to use data from Toronto's Watch Your Speed Program (WYSP) to investigate the relationship between traffic direction, prevalence of high-speed vehicles, and median driving speeds. It was found that North/Southbound traffic was correlated with higher median speeds then eastbound, and that more high-speed vehicles were correlated with a higher median speed.

**Strong positive points**:

- Good job making sure that preambles of scripts are updated
- Good job with the formatting of the paper - it is quite well organised.
- Very good prose, it is quite well-written.

 **Critical improvements needed:**
- table 1 should be in the model section. I'm assuming it uses the modelsummary() function, so it would likely be better there.
- From Figure 2 it is quite hard to decipher a between the amount of vehicles over 100 km/h and the median speed.
-  make sure to update sketches of graphs/dataset from the default

 **Suggestions for improvement:**

- If possible, transform the 'count of vehicles over 100km/h' in figure 2 to into a proportion/percentage (might show a better relationship)
- Consider having more information on the model's limitations (in the model section)
- Consider having more tables/graphs/etc. in the results section (instead of just the modelsummary() output)
- Try to reference more literature in the surveys appendix section
- In the abstract it may be good to include that although north/south speeds have a higher median, it is not by much 

 **Evaluation:**
R is appropriately cited (1 pts): 
1/1: R is appropriately cited in the bibliography and in the paper

Data  is appropriately cited (1 pts):
1/1: data is appropriately cited in the bibliography and in the paper

Class paper (1 pts):
1/1: No indication this is a class project

LLM usage documented (1 pts):
1/1: It is mentioned that LLM usage was not involved for this paper.

Title (2 pts):
2/2: The title is concise and informative

Author, date, and repo (2 pts):
2/2: The author, date, and GitHub repo link are included.

Abstract (4 pts):
3/4: Overall pretty good, but I believe it could be better by more accurately showing the results that you found (as mentioned in critical improvements needed)

Introduction (4 pts):
4/4: The introduction shows the significance and the broader context to motivate. It also shows the paper's structure and results of the paper as well. Nice!

Estimand (1 pts):
1/1: The estimand (conditional median speed) is mentioned and explained.

Data (10 pts):
8.5/10: Quite well done! Consider the changes I mentioned above that you could use to make the graphs more obvious as to what they are trying to show. This could help the reader have a better grasp of the dataset and how it connects to your results/discussion.

Measurement (4 pts):
4/4: Quite in depth and provides a good overview of how this data was obtained/measured.

Model (10 pts):
8/10: This is quite well done, but consider having some more information on the limitations of the model. Also make sure to have evidence of model validation.

Results (10 pts):
7/10: Although the results have been summarised in table 1, table 1 is the output of modelsummary(). Perhaps more of the results could be conveyed as a table? For example, you could portray the average speed depending on direction as a table.

Discussion (10 pts):
9.5/10: Very well done! Some small nit-picky things such as mentioning that the difference in median speed based on direction is quite small.

Prose (6 pts):
5.9/6: Overall great pose — there are a very small number of spelling mistakes, though.

Cross-references (1 pts):
1/1: Cross-references are included

Captions (2 pts):
2/2: Captions are descriptive and communicate what the graph is about

Graphs/tables/etc (4 pts):
3/4: Overall quite good but could be improved to give a better grasp of the data.

Surveys, sampling, and observational data appendix (10 pts):
8/10: Quite good, but make sure to reference more literature that relates to the study.

Referencing (4 pts):
4/4: No errors

Commits (2 pts):
1/2: Make sure to have more descriptive commit messages.

Sketches (2 pts):
0/2: The paper does not have relevant sketches.

Simulation (4 pts):
4/4: The paper has good and relevant simulations

Tests (4 pts):
3/4: Tests were provided, but consider having more thorough/advanced tests.

Parquet (1 pts):
1/1: raw data and analysis data are both present.

Reproducible workflow (4 pts):
3/4: Generally reproducible workflow but make sure to add set.seed() in simulations

Miscellaneous (3 pts):
3/3: Presence of API's in model folder is quite impressive.

Enhancements (4 pts):
4/4: API enhancement was done for this paper.

**Estimated overall mark:**
95.9/112.

**Other Comments** 

This was overall a very well done paper, and I am impressed you are able to already finish this much of the paper despite the deadline being December 1st. I believe if you fix up some small errors then your grade will be even higher. 

Good luck with the paper! I hope some of my feedback can help. :)

**Comment by Stella41603** [comment]
Thank you for your review, changes were made accordingly.
